// <auto-generated />
using ECommerceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceApi.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20260804140752_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ECommerceApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("ECommerceApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Product 1",
                            Price = 15m,
                            StockQuantity = 99
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Name = "Product 2",
                            Price = 20m,
                            StockQuantity = 98
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Name = "Product 3",
                            Price = 25m,
                            StockQuantity = 97
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Product 4",
                            Price = 30m,
                            StockQuantity = 96
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Product 5",
                            Price = 35m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Product 6",
                            Price = 40m,
                            StockQuantity = 94
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Product 7",
                            Price = 45m,
                            StockQuantity = 93
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Product 8",
                            Price = 50m,
                            StockQuantity = 92
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Product 9",
                            Price = 55m,
                            StockQuantity = 91
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Name = "Product 10",
                            Price = 60m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Product 11",
                            Price = 65m,
                            StockQuantity = 89
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Product 12",
                            Price = 70m,
                            StockQuantity = 88
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Name = "Product 13",
                            Price = 75m,
                            StockQuantity = 87
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "Product 14",
                            Price = 80m,
                            StockQuantity = 86
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Product 15",
                            Price = 85m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Name = "Product 16",
                            Price = 90m,
                            StockQuantity = 84
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Name = "Product 17",
                            Price = 95m,
                            StockQuantity = 83
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Name = "Product 18",
                            Price = 100m,
                            StockQuantity = 82
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Name = "Product 19",
                            Price = 105m,
                            StockQuantity = 81
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Name = "Product 20",
                            Price = 110m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Name = "Product 21",
                            Price = 115m,
                            StockQuantity = 79
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Name = "Product 22",
                            Price = 120m,
                            StockQuantity = 78
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Name = "Product 23",
                            Price = 125m,
                            StockQuantity = 77
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Name = "Product 24",
                            Price = 130m,
                            StockQuantity = 76
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Name = "Product 25",
                            Price = 135m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Name = "Product 26",
                            Price = 140m,
                            StockQuantity = 74
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Name = "Product 27",
                            Price = 145m,
                            StockQuantity = 73
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            Name = "Product 28",
                            Price = 150m,
                            StockQuantity = 72
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Name = "Product 29",
                            Price = 155m,
                            StockQuantity = 71
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Name = "Product 30",
                            Price = 160m,
                            StockQuantity = 70
                        });
                });

            modelBuilder.Entity("ECommerceApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Rating = 2,
                            ReviewerName = "User1"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Rating = 3,
                            ReviewerName = "User2"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Rating = 4,
                            ReviewerName = "User3"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Rating = 5,
                            ReviewerName = "User4"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Rating = 1,
                            ReviewerName = "User5"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Rating = 2,
                            ReviewerName = "User6"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Rating = 3,
                            ReviewerName = "User7"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Rating = 4,
                            ReviewerName = "User8"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Rating = 5,
                            ReviewerName = "User9"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Rating = 1,
                            ReviewerName = "User10"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 11,
                            Rating = 2,
                            ReviewerName = "User11"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 12,
                            Rating = 3,
                            ReviewerName = "User12"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 13,
                            Rating = 4,
                            ReviewerName = "User13"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 14,
                            Rating = 5,
                            ReviewerName = "User14"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 15,
                            Rating = 1,
                            ReviewerName = "User15"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 16,
                            Rating = 2,
                            ReviewerName = "User16"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 17,
                            Rating = 3,
                            ReviewerName = "User17"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 18,
                            Rating = 4,
                            ReviewerName = "User18"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 19,
                            Rating = 5,
                            ReviewerName = "User19"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 20,
                            Rating = 1,
                            ReviewerName = "User20"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 21,
                            Rating = 2,
                            ReviewerName = "User21"
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 22,
                            Rating = 3,
                            ReviewerName = "User22"
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 23,
                            Rating = 4,
                            ReviewerName = "User23"
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 24,
                            Rating = 5,
                            ReviewerName = "User24"
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 25,
                            Rating = 1,
                            ReviewerName = "User25"
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 26,
                            Rating = 2,
                            ReviewerName = "User26"
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 27,
                            Rating = 3,
                            ReviewerName = "User27"
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 28,
                            Rating = 4,
                            ReviewerName = "User28"
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 29,
                            Rating = 5,
                            ReviewerName = "User29"
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 30,
                            Rating = 1,
                            ReviewerName = "User30"
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 1,
                            Rating = 2,
                            ReviewerName = "User31"
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 2,
                            Rating = 3,
                            ReviewerName = "User32"
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 3,
                            Rating = 4,
                            ReviewerName = "User33"
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 4,
                            Rating = 5,
                            ReviewerName = "User34"
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 5,
                            Rating = 1,
                            ReviewerName = "User35"
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 6,
                            Rating = 2,
                            ReviewerName = "User36"
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 7,
                            Rating = 3,
                            ReviewerName = "User37"
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 8,
                            Rating = 4,
                            ReviewerName = "User38"
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 9,
                            Rating = 5,
                            ReviewerName = "User39"
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 10,
                            Rating = 1,
                            ReviewerName = "User40"
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 11,
                            Rating = 2,
                            ReviewerName = "User41"
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 12,
                            Rating = 3,
                            ReviewerName = "User42"
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 13,
                            Rating = 4,
                            ReviewerName = "User43"
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 14,
                            Rating = 5,
                            ReviewerName = "User44"
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 15,
                            Rating = 1,
                            ReviewerName = "User45"
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 16,
                            Rating = 2,
                            ReviewerName = "User46"
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 17,
                            Rating = 3,
                            ReviewerName = "User47"
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 18,
                            Rating = 4,
                            ReviewerName = "User48"
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 19,
                            Rating = 5,
                            ReviewerName = "User49"
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 20,
                            Rating = 1,
                            ReviewerName = "User50"
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 21,
                            Rating = 2,
                            ReviewerName = "User51"
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 22,
                            Rating = 3,
                            ReviewerName = "User52"
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 23,
                            Rating = 4,
                            ReviewerName = "User53"
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 24,
                            Rating = 5,
                            ReviewerName = "User54"
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 25,
                            Rating = 1,
                            ReviewerName = "User55"
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 26,
                            Rating = 2,
                            ReviewerName = "User56"
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 27,
                            Rating = 3,
                            ReviewerName = "User57"
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 28,
                            Rating = 4,
                            ReviewerName = "User58"
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 29,
                            Rating = 5,
                            ReviewerName = "User59"
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 30,
                            Rating = 1,
                            ReviewerName = "User60"
                        },
                        new
                        {
                            Id = 61,
                            ProductId = 1,
                            Rating = 2,
                            ReviewerName = "User61"
                        },
                        new
                        {
                            Id = 62,
                            ProductId = 2,
                            Rating = 3,
                            ReviewerName = "User62"
                        },
                        new
                        {
                            Id = 63,
                            ProductId = 3,
                            Rating = 4,
                            ReviewerName = "User63"
                        },
                        new
                        {
                            Id = 64,
                            ProductId = 4,
                            Rating = 5,
                            ReviewerName = "User64"
                        },
                        new
                        {
                            Id = 65,
                            ProductId = 5,
                            Rating = 1,
                            ReviewerName = "User65"
                        },
                        new
                        {
                            Id = 66,
                            ProductId = 6,
                            Rating = 2,
                            ReviewerName = "User66"
                        },
                        new
                        {
                            Id = 67,
                            ProductId = 7,
                            Rating = 3,
                            ReviewerName = "User67"
                        },
                        new
                        {
                            Id = 68,
                            ProductId = 8,
                            Rating = 4,
                            ReviewerName = "User68"
                        },
                        new
                        {
                            Id = 69,
                            ProductId = 9,
                            Rating = 5,
                            ReviewerName = "User69"
                        },
                        new
                        {
                            Id = 70,
                            ProductId = 10,
                            Rating = 1,
                            ReviewerName = "User70"
                        },
                        new
                        {
                            Id = 71,
                            ProductId = 11,
                            Rating = 2,
                            ReviewerName = "User71"
                        },
                        new
                        {
                            Id = 72,
                            ProductId = 12,
                            Rating = 3,
                            ReviewerName = "User72"
                        },
                        new
                        {
                            Id = 73,
                            ProductId = 13,
                            Rating = 4,
                            ReviewerName = "User73"
                        },
                        new
                        {
                            Id = 74,
                            ProductId = 14,
                            Rating = 5,
                            ReviewerName = "User74"
                        },
                        new
                        {
                            Id = 75,
                            ProductId = 15,
                            Rating = 1,
                            ReviewerName = "User75"
                        },
                        new
                        {
                            Id = 76,
                            ProductId = 16,
                            Rating = 2,
                            ReviewerName = "User76"
                        },
                        new
                        {
                            Id = 77,
                            ProductId = 17,
                            Rating = 3,
                            ReviewerName = "User77"
                        },
                        new
                        {
                            Id = 78,
                            ProductId = 18,
                            Rating = 4,
                            ReviewerName = "User78"
                        },
                        new
                        {
                            Id = 79,
                            ProductId = 19,
                            Rating = 5,
                            ReviewerName = "User79"
                        },
                        new
                        {
                            Id = 80,
                            ProductId = 20,
                            Rating = 1,
                            ReviewerName = "User80"
                        },
                        new
                        {
                            Id = 81,
                            ProductId = 21,
                            Rating = 2,
                            ReviewerName = "User81"
                        },
                        new
                        {
                            Id = 82,
                            ProductId = 22,
                            Rating = 3,
                            ReviewerName = "User82"
                        },
                        new
                        {
                            Id = 83,
                            ProductId = 23,
                            Rating = 4,
                            ReviewerName = "User83"
                        },
                        new
                        {
                            Id = 84,
                            ProductId = 24,
                            Rating = 5,
                            ReviewerName = "User84"
                        },
                        new
                        {
                            Id = 85,
                            ProductId = 25,
                            Rating = 1,
                            ReviewerName = "User85"
                        },
                        new
                        {
                            Id = 86,
                            ProductId = 26,
                            Rating = 2,
                            ReviewerName = "User86"
                        },
                        new
                        {
                            Id = 87,
                            ProductId = 27,
                            Rating = 3,
                            ReviewerName = "User87"
                        },
                        new
                        {
                            Id = 88,
                            ProductId = 28,
                            Rating = 4,
                            ReviewerName = "User88"
                        },
                        new
                        {
                            Id = 89,
                            ProductId = 29,
                            Rating = 5,
                            ReviewerName = "User89"
                        },
                        new
                        {
                            Id = 90,
                            ProductId = 30,
                            Rating = 1,
                            ReviewerName = "User90"
                        });
                });

            modelBuilder.Entity("ECommerceApi.Models.Product", b =>
                {
                    b.HasOne("ECommerceApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerceApi.Models.Review", b =>
                {
                    b.HasOne("ECommerceApi.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceApi.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
